spring:
  application:
    name: sleuth-example-001
  zipkin: # 将zipkin 所有都注释掉，默认是localhost:9441
    #base-url: http://localhost:5000
    #base-url: http://localhost:4999   # 下面是发送到kafka 所以base-url不需要
    sender:
      type: kafka  # 采集数据异步发送到kafka，不采用kafka 将其注释掉就可以了，支持三种 方式  RABBIT, KAFKA, WEB
    kafka:
      topic: zipkin  # 发送的kafka  topic
  kafka:
     bootstrap-servers: 10.12.52.21:9092
  sleuth:
    sampler:
      probability: 1 #设置采样率，为了测试设置100%采集，设置为1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 5001
