spring:
  application:
    name: eureka-consumer007
server:
  port: 8006
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

ribbon:
  maxAutoRetries: 0
  maxAutoRetriesNextServer: 0
  okToRetryOnAllOperations: false
  connectTimeout: 3000
  readTimeout: 3000
eureka-producer:
  ribbon:
    connectTimeout: 5000 #请求连接超时时间
    readTimeout: 3000 #请求处理的超时时间