spring:
  application:
    name: zipkin-server-mysql-kf
  sleuth:
    enabled: false #表示当前程序不使用sleuth
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sleuth?characterEncoding=utf-8&useSSL=false
    initialize: true
  kafka:
    bootstrap-servers: 10.12.52.21:9092
zipkin:
  storage:
    type: mysql
  collector:
    kafka:
      topic: zipkin
      groupId: zipkin-group
      streams: 3 # consumer thread number
      bootstrap-servers: 10.12.52.21:9092
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 4888
management:
  metrics:
    web:
      server:
        auto-time-requests: false
