spring:
  application:
    name: stream-example-005
  kafka:
    bootstrap-servers: 10.12.52.21:9092
  cloud:
    stream:
      instance-count: 2 # 实例数，也就是分区数
      bindings:
        output:
          content-type: application/json
          destination: test5
          producer:
            partitionCount: 2  # 分区数量
            partitionKeyExpression: headers['partitionKey'] # 分区表达式
            #partitionKeyExtractorClass: com.jufeng.cloud.stream005.MyPartitionKeyExtractor
            #partitionSelectorClass: com.jufeng.cloud.stream005.MyPartitionKeyExtractor
server:
  port: 2005
