spring:
  application:
    name: zipkin-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 5000
management:
  metrics:
    web:
      server:
        auto-time-requests: false
