spring:
  application:
    name: stream-example-012
  #kafka:
    #bootstrap-servers: 10.12.52.21:9092
  cloud:
    stream:
      kafka: # 设置kafka binder
        binder:
          brokers: 10.12.52.21:9092, 10.12.52.22:9092, 10.12.52.23:9092
          defaultBrokerPort: 9092
          zkNodes: 10.12.52.21:2181, 10.12.52.22:2181, 10.12.52.23:2181
          defaultZkPort: 2181
      bindings:
        input:
          destination: test12
          group: group-aa
          consumer:
            maxAttempts: 1 # 直接接受一次
        output:
          destination: test12
server:
  port: 2012
