spring:
  application:
    name: eureka-server
server:
  port: 7000
eureka:
  instance:
    perferIpAddress: true
    #hostname:  ${spring.cloud.client.ipAddress}
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/, http://localhost:7002/eureka/