spring:
  application:
    name: eureka-server
server:
  port: 7001
eureka:
  instance:
    perferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/, http://localhost:7002/eureka/