spring:
  application:
    name: eureka-server
server:
  port: 7002
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/,http://localhost:7001/eureka/