spring:
  application:
    name: stream-example-006
  kafka:
    bootstrap-servers: 10.12.52.21:9092
  cloud:
    stream:
      instance-index: 0  # 从哪个分区接受数据
      instance-count: 2 # 实例数，也就是分区数
      bindings:
        input:
          destination: test5
          group: group-a
          consumer:
            partitioned: true # 是否接受来自分区的数据
server:
  port: 2006
