spring:
  application:
    name: stream-example-008
  kafka:
    bootstrap-servers: 10.12.52.21:9092
  cloud:
    stream:
      bindings:
        input:
          destination: test8
        output:
          destination: test8
server:
  port: 2008
