spring:
  application:
    name: proxy-001
server:
  port: 3001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有端点 默认是info,health
ribbon:  # Zuul Http Client 默认是 Apache HTTP Client
  restclient:
    enabled: false
  okhttp:
    enabled: true
zuul:
  retryable: true # 开启全局的重试
  ignoredServices: '*' # 不开放所有的服务，只是开放了下面配置的users
  ignored-patterns:  /**/oauth/token,/gateway/push/**  # 过滤某些url，不进行代理，也就是不对外进行开放
  ribbon:
    eager-load:
      enabled: true  # ribbon 不进行延迟初始化
  threadPool:
    useSeparateThreadPools: true
    threadPoolKeyPrefix: zuulgw
  routes:
    users: # 这里随便起，也可以写成server-id，下面的额serviceId 就可以不写了
      path: /user/**
      sensitiveHeaders: Cookie,Set-Cookie,Authorization  #过滤客户端的header
      ignoredHeaders: Authorization  # 过滤服务端的header，也就是代理层的header
      stripPrefix: false   # 不跳过user 前缀
      serviceId: user-server

hystrix:
  command:
    user-server:  # 服务id
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8005
# 设置user-server代理的超时时间
user-server:
  ribbon:
    #NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    #listOfServers: https://example1.com,http://example2.com
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
    OkToRetryOnAllOperations: true #对所有请求都进行重试
    MaxAutoRetriesNextServer: 2 #切换实例的重试次数
    MaxAutoRetries: 1 #对当前实例的重试次数