spring:
  application:
    name: zookeeper-example-003
  cloud:
    zookeeper:
      connect-string: localhost:2181
server:
  port: 6003
zookeeper-example-001:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
