spring:
  application:
    name: hystrix-consumer004
server:
  port: 7004
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
hystrix:
  command:
    default:
      requestCache:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有端点 默认是info,health