spring:
  application:
    name: eureka-consumer007
server:
  port: 8004
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

feign:
  httpclient:
    enable: false
  okhttp:
    enabled: true
    # 最大连接数
    max-connections: 200
    # 单个路径的最大连接数
    max-connections-per-route: 50