spring:
  application:
    name: hystrix-consumer005
server:
  port: 7005
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
feign:
  hystrix:
    enabled: true  #打开hystrix
hystrix:
  command:
    UserService#getName(): # 设置hystrix 超时 走callback的超时 时间
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
            interruptOnTimeout: true  # 超时之后是否中断线程请求